### ISSUE TITLE
:clown:

### ISSUE THREAD

**Issue by fuckyouthinkimboogieman** [PlutoSolutions/legacy-hvh-rip#1]
retarded pigs publishing my jar from https://github.com/fuckyouthinkimboogieman/legacy-leak and decompiling src by cfr and publishing it and not even removing comments 🤡

**Comment by fuckyouthinkimboogieman** [comment]
credit me and lemoliam or pig

**Comment by oyzipfile** [comment]
Иссуе закрыто, вы имеете low brain

**Comment by fuckyouthinkimboogieman** [comment]
пидорас ебаный
